#!/usr/bin/env sh

set -ex

while read -r alpine_version mod_pagespeed_tag;
do
  image=${DOCKER_REPO}:alpine-${alpine_version}-${mod_pagespeed_tag}
  echo "# Pushing image ${image}..."

  docker image push "${image}"
done < VERSION_MATRIX
